version: '3.5'

services:
  syncer:
    image: ssync/ssync:0.2.1
    build:
      context: .
    volumes:
      - ./docker-entrypoint.sh:/docker-entrypoint.sh
      - ./test:/src:cached
      - code:/dest
      - unison:/unison_data
    command: watch
    environment:
      - USERID=1000
      - USERNAME=julian
      - UNISON_OPTS=-ignore "Path .git" -ignore "Path tags*" -ignore "Name {.*,*}.sw[pon]" -ignore "Path tmp" -prefer /src

volumes:
  code:
  unison:
